

local function animate()
	spine.play_anim("#spine", "Flight", go.PLAYBACK_LOOP_FORWARD, { blend_duration = 0.2 })
	timer.delay(math.random(1, 4), false, function()
		spine.play_anim("#spine", "Idle", go.PLAYBACK_LOOP_FORWARD, { blend_duration = 0.2 })
		timer.delay(math.random(1, 4), false, function()
			animate()
		end)
	end)
end

function init(self)
	spine.play_anim("#spine", "Idle", go.PLAYBACK_LOOP_FORWARD)
	animate()
end
