local M = {}
M.WINDOW_RESIZED = "WINDOW_RESIZED"

M.BATTLE_WORD_CHANGED = "BATTLE_WORD_CHANGED"
M.STORAGE_UPDATED = "STORAGE_UPDATED"
M.TTS_MARK = "TTS_MARK"
M.SCENE_CHANGED = "SCENE_CHANGED"
M.CONTINUOUS_MODE_MATCHED = "CONTINUOUS_MODE_MATCHED"
M.MAP_REGION_CHANGED = "MAP_REGION_CHANGED"

return M